// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Racinglazing.Forum.Infrastructure.Persistence;

#nullable disable

namespace Racinglazing.Forum.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ForumDbContext))]
    [Migration("20260910171620_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Racinglazing.Forum.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<int>("ForumCount")
                        .HasColumnType("integer")
                        .HasColumnName("forum_count");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("slug");

                    b.Property<long>("ThreadCount")
                        .HasColumnType("bigint")
                        .HasColumnName("thread_count");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_slug");

                    b.HasIndex("IsActive", "DisplayOrder")
                        .HasDatabaseName("ix_categories_is_active_display_order");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Racinglazing.Forum.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("author_id");

                    b.Property<double>("ControversyScore")
                        .HasColumnType("double precision")
                        .HasColumnName("controversy_score");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("Depth")
                        .HasColumnType("integer")
                        .HasColumnName("depth");

                    b.Property<int>("DownvoteCount")
                        .HasColumnType("integer")
                        .HasColumnName("downvote_count");

                    b.Property<double>("HotScore")
                        .HasColumnType("double precision")
                        .HasColumnName("hot_score");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("boolean")
                        .HasColumnName("is_edited");

                    b.Property<bool>("IsRoot")
                        .HasColumnType("boolean")
                        .HasColumnName("is_root");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_comment_id");

                    b.Property<int>("ReplyCount")
                        .HasColumnType("integer")
                        .HasColumnName("reply_count");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uuid")
                        .HasColumnName("thread_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpvoteCount")
                        .HasColumnType("integer")
                        .HasColumnName("upvote_count");

                    b.HasKey("Id")
                        .HasName("pk_comments");

                    b.HasIndex("ParentCommentId", "CreatedAt", "Id")
                        .HasDatabaseName("ix_comments_replies_new");

                    b.HasIndex("ParentCommentId", "Score", "Id")
                        .HasDatabaseName("ix_comments_replies_top");

                    b.HasIndex("ThreadId", "ParentCommentId", "IsRoot", "CreatedAt", "Id")
                        .HasDatabaseName("ix_comments_thread_new");

                    b.HasIndex("ThreadId", "ParentCommentId", "IsRoot", "Score", "Id")
                        .HasDatabaseName("ix_comments_thread_top");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("Racinglazing.Forum.Domain.Entities.Forum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<long>("PostCount")
                        .HasColumnType("bigint")
                        .HasColumnName("post_count");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("slug");

                    b.Property<long>("ThreadCount")
                        .HasColumnType("bigint")
                        .HasColumnName("thread_count");

                    b.HasKey("Id")
                        .HasName("pk_forums");

                    b.HasIndex("CategoryId", "DisplayOrder")
                        .HasDatabaseName("ix_forums_category_id_display_order");

                    b.HasIndex("CategoryId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_forums_category_id_slug");

                    b.ToTable("forums", (string)null);
                });

            modelBuilder.Entity("Racinglazing.Forum.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<int>("Reason")
                        .HasColumnType("integer")
                        .HasColumnName("reason");

                    b.Property<string>("ReportedByUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("reported_by_user_id");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("ResolvedByUserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("resolved_by_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer")
                        .HasColumnName("target_type");

                    b.HasKey("Id")
                        .HasName("pk_reports");

                    b.HasIndex("Status", "TargetType", "CreatedAt", "Id")
                        .HasDatabaseName("ix_reports_queue");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("Racinglazing.Forum.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<long>("ThreadCount")
                        .HasColumnType("bigint")
                        .HasColumnName("thread_count");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_tags_name");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_slug");

                    b.HasIndex("ThreadCount")
                        .HasDatabaseName("ix_tags_thread_count");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Racinglazing.Forum.Domain.Entities.Thread", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("author_id");

                    b.Property<int>("CommentCount")
                        .HasColumnType("integer")
                        .HasColumnName("comment_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("DownvoteCount")
                        .HasColumnType("integer")
                        .HasColumnName("downvote_count");

                    b.Property<Guid>("ForumId")
                        .HasColumnType("uuid")
                        .HasColumnName("forum_id");

                    b.Property<double>("HotScore")
                        .HasColumnType("double precision")
                        .HasColumnName("hot_score");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_locked");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pinned");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<string>("LockReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("lock_reason");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_at");

                    b.Property<string>("RaceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("race_id");

                    b.Property<Guid?>("RootCommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("root_comment_id");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(340)
                        .HasColumnType("character varying(340)")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpvoteCount")
                        .HasColumnType("integer")
                        .HasColumnName("upvote_count");

                    b.Property<long>("ViewCount")
                        .HasColumnType("bigint")
                        .HasColumnName("view_count");

                    b.HasKey("Id")
                        .HasName("pk_threads");

                    b.HasIndex("ForumId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_threads_forum_id_slug");

                    b.HasIndex("ForumId", "IsDeleted", "IsPinned", "CommentCount", "Id")
                        .HasDatabaseName("ix_threads_forum_commented");

                    b.HasIndex("ForumId", "IsDeleted", "IsPinned", "CreatedAt", "Id")
                        .HasDatabaseName("ix_threads_forum_new");

                    b.HasIndex("ForumId", "IsDeleted", "IsPinned", "HotScore", "Id")
                        .HasDatabaseName("ix_threads_forum_hot");

                    b.HasIndex("ForumId", "IsDeleted", "IsPinned", "LastActivityAt", "Id")
                        .HasDatabaseName("ix_threads_forum_updated");

                    b.HasIndex("ForumId", "IsDeleted", "IsPinned", "Score", "Id")
                        .HasDatabaseName("ix_threads_forum_top");

                    b.HasIndex("RaceId", "IsDeleted", "IsPinned", "HotScore", "Id")
                        .HasDatabaseName("ix_threads_race_hot");

                    b.ToTable("threads", (string)null);
                });

            modelBuilder.Entity("Racinglazing.Forum.Domain.Entities.ThreadTag", b =>
                {
                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uuid")
                        .HasColumnName("thread_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("ThreadId", "TagId")
                        .HasName("pk_thread_tags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_thread_tags_tag_id");

                    b.ToTable("thread_tags", (string)null);
                });

            modelBuilder.Entity("Racinglazing.Forum.Domain.Entities.Vote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer")
                        .HasColumnName("target_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_id");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_votes");

                    b.HasIndex("TargetType", "TargetId")
                        .HasDatabaseName("ix_votes_target_type_target_id");

                    b.HasIndex("UserId", "TargetType", "TargetId")
                        .IsUnique()
                        .HasDatabaseName("ix_votes_user_id_target_type_target_id");

                    b.ToTable("votes", (string)null);
                });

            modelBuilder.Entity("Racinglazing.Forum.Domain.Entities.Comment", b =>
                {
                    b.HasOne("Racinglazing.Forum.Domain.Entities.Comment", null)
                        .WithMany()
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_comments_comments_parent_comment_id");

                    b.HasOne("Racinglazing.Forum.Domain.Entities.Thread", null)
                        .WithMany()
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_threads_thread_id");

                    b.OwnsOne("Racinglazing.Forum.Domain.Entities.CommentContent", "Content", b1 =>
                        {
                            b1.Property<Guid>("CommentId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(40000)
                                .HasColumnType("character varying(40000)")
                                .HasColumnName("content_text");

                            b1.HasKey("CommentId");

                            b1.ToTable("comments");

                            b1.WithOwner()
                                .HasForeignKey("CommentId")
                                .HasConstraintName("fk_comments_comments_id");
                        });

                    b.Navigation("Content")
                        .IsRequired();
                });

            modelBuilder.Entity("Racinglazing.Forum.Domain.Entities.Forum", b =>
                {
                    b.HasOne("Racinglazing.Forum.Domain.Entities.Category", "Category")
                        .WithMany("Forums")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_forums_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Racinglazing.Forum.Domain.Entities.Thread", b =>
                {
                    b.HasOne("Racinglazing.Forum.Domain.Entities.Forum", "Forum")
                        .WithMany()
                        .HasForeignKey("ForumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_threads_forums_forum_id");

                    b.Navigation("Forum");
                });

            modelBuilder.Entity("Racinglazing.Forum.Domain.Entities.ThreadTag", b =>
                {
                    b.HasOne("Racinglazing.Forum.Domain.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_thread_tags_tags_tag_id");

                    b.HasOne("Racinglazing.Forum.Domain.Entities.Thread", "Thread")
                        .WithMany("ThreadTags")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_thread_tags_threads_thread_id");

                    b.Navigation("Tag");

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("Racinglazing.Forum.Domain.Entities.Category", b =>
                {
                    b.Navigation("Forums");
                });

            modelBuilder.Entity("Racinglazing.Forum.Domain.Entities.Thread", b =>
                {
                    b.Navigation("ThreadTags");
                });
#pragma warning restore 612, 618
        }
    }
}
